### ISSUE TITLE
Energy IoT Open Source

### ISSUE THREAD

**Issue by axmsoftware** [lf-energy/tac#113]
### Mission Statement

Energy IoT Open Source is a non-profit that manages the open source program to enable and accelerate the open source development of software and hardware for Energy IoT as a basic platform for democratizing the microgrid for micro-utility sites.  
  The main goals are to accelerate the affordability, health, and access to microgrids everywhere.		 	 	
  Energy IoT or Energy Internet of Things requires the same security rigor as industrial IoT and the affordability of consumer IoT. 

### Description

The focus of Energy IoT Open Source is the open source program to enable and accelerate the open source development of software and hardware for Energy IoT as a basic platform for democratizing the microgrid for small and medium sites.  The main goals are to accelerate the affordability, health, and access to microgrids everywhere.		 	 	
Energy IoT or Energy Internet of Things requires the same security rigor as industrial IoT and the affordability of consumer IoT. 
This project aims to focus on the integration of multiple LF Energy projects to provide the core features required to manage any microgrid: energy management, communication management, and protocol management.  
The project addresses horizontal concerns such as security, end-point protection, packaging, deployment, testing, and benchmarking of other open source projects which focus on specific features like energy management.  It also provides a virtual simulation environment to verify the safety of the Energy IoT before it is packaged for use at a site.  In addition to projects available in the LF Energy ecosystem,  Energy IoT bridges other open source projects like OpenEMS. 
Energy IoT is an accelerator for both open source and commercial projects that aim at providing microgrid solutions in the field.  In addition to the software packaging, the project also aims to collaborate on the hardware open source specification to further reduce the cost of microgrid site controllers.

### Is this a new project or an existing one?

new

### Current lead(s)

Arila Barnes

### Sponsoring organization(s), along with any other key contributing individuals and/or organizations

Energy IoT Open Source, AXM Software LLC, Kaleidoscope Inc.
Arila Barnes, Bello Afeez, Aidan Barnes, Mia Maksumova, Suparna Pal

### Detail any existing community infrastructure, including:
  - Github/GitLab, or other location where the code is hosted
  - Website and/or docs
  - Communication channels ( such as Mailing lists, Slack, IRC )
  - Social Media Accounts

[https://github.com/energy-iot/](url)
[www.eiot.energy](url)

### Are there any specific infrastructure needs or requests outside of what is provided normally by LF Energy ? If so please detail them.

No

### Why would this be a good candidate for inclusion in LF Energy?

This will be a system that contributes to standardizing and accelerating microgrids that integrate well with the existing grid infrastructure as needed.
It provides all the deployments and simulation environments as Infrastructure as Code and docker containers to allow the Open Source community to test and benchmark safety critical functionality before testing in the field. It will reduce time to commission microgrid projects as the library of of microgrid site configurations grows. It will also reduce cost since we provide a lot of community validated building blocks for both hardware and software.

### How would this benefit from inclusion in LF Energy?

The inclusion of the Energy IoT Open Source project in LF Energy will provide access to a platform and enable a community for collaboration within and across sectors which is a great possibility to accelerate the quality of the dependency projects directly and the green transition indirectly

### Provide a statement on alignment with the mission in the LF Energy charter.

The project aligns with the LF Energy mission as it helps to accelerate the green transition through microgrid acceleration. The Energy IoT Open Source enables the micro-utilities in the energy disadvantaged communities.

### What specific need does this project address?

Energy IoT Open Source provides the following benefits to the LF Energy open source community:

- Infrastructure as Code - to accelerate deployment of containerized LF Energy dependency project
- End-to-End Security in virtual cloud environments and on Energy IoT Open Source hardware IoT devices
- Virtual Test Lab - to accelerate safety compliance and edge IoT device configurations
- Standards based integration ecosystem for data and communications.

### Describe how this project impacts the energy industry.

Energy IoT shortens the time to market for energy management functionality required for microgrids to interact with the main grid and other renewable energy equipment as it is added and removed from microgrid sites by automating the security, packaging, and deployment of dependent open source projects.

### Describe how this project intersects with other LF Energy projects/working groups/special interest groups.

Energy IoT Open Source packages and integrates several LF Energy projects in a single solution to address the microgrid space.

### Who are the potential benefactors of this project?

The main beneficiaries of this project are Microgrid site developers and implementers. Technology companies and entities developing energy management systems and microgrid systems that need to interact with the central grid.

### What other organizations in the world should be interested in this project?

We anticipate community micro-utilities and vendor-agnostic companies that provide microgrid project solutions to leverage Energy IoT Open Source.

### Plan for growing in maturity if accepted within LF Energy

The plan is to go from Sandbox stage to Incubation stage within the next 6-12 months.
Expected main challenge: growing in the project´s community and gaining traction in the industry.

### Project license

Apache v. 2.0

### Is the project's code available now? If so provide a link to the code location.

[https://github.com/energy-iot/](url)

### Does this project have ongoing public (or private) technical meetings?

Yes, private meetings inside Energy IoT Open Source, but decisions are visible on Energy IoT: https://github.com/energy-iot/docs/tree/main/architecture-decision-record

### Does this project's community venues have a code of conduct? If so, please provide a link to it?

[https://github.com/energy-iot/docs/wiki/Code-of-Conduct](url)

### Describe the project's leadership team and decision-making process.

Energy IoT Open Source uses the Scaled Agile Framework (SAFe) to lead the project via a program management office  with scrum teams composed of volunteers. See [https://github.com/energy-iot/docs/wiki/Energy-IoT-Open-Source-Policy](url) for details.
The Steering Group is established with AXM Software LLC and Kaleidoscope Inc. to ensure contributions from the open source community are prioritized according to the goals, purpose, and strategy for the Energy IoT Open Source.

### Does this project have public governance (more than just one organization)?

Yes

### Does this project have a development schedule and/or release schedule?

Yes, the expected release date: June 2024

### Does this project have dependencies on other open source projects? Which ones?

Yes. Energy IoT Open Source integrates both LF Energy projects (OpenLEADR, FlexMeasures) and other OSS initiatives like  OpenEMS and OpenEDR.

### Describe the project's documentation.

[https://github.com/energy-iot/docs](url)

### Describe any trademarks associated with the project.

None

### Do you have a project roadmap? If so please attach or provide a link.

The solution roadmap can be found here:
[https://github.com/orgs/energy-iot/projects/1](url)

### Are this project's roadmap and meeting minutes public posted?

Yes, GitHub project is used to track progress. See [https://github.com/orgs/energy-iot/projects/1](url)

### Does this project have a legal entity and/or registered trademarks?

Yes, Energy IoT Open Source is registered as a California Non-Profit business entity.

### Has this project been announced or promoted in any press?

ClimateLink Meetup Mixer (01/11/2023) Pitch

### Does this project compete with other open source projects or commercial products?

No

**Comment by yarille** [comment]
Hello, @axmsoftware. Would April 23 work for you? Can you provide me with names and emails for those who will present?

**Comment by yarille** [comment]
Arila will follow up with Anto to schedule a meeting to discuss the project.

**Comment by jmertic** [comment]
Great to hear! I will add this to the agenda for the June 4th TAC meeting for discussion if that timing works for you.

**Comment by axmsoftware** [comment]
Hi John,

The June 4th TAC date works for me.  Please confirm the time.

Thank you,

Arila

**Comment by jmertic** [comment]
Same time as before - 11am US Eastern - link to join/register at https://zoom-lfx.platform.linuxfoundation.org/meeting/95214651568?password=eda16f17-bdd1-4a9f-a594-0947a1433153

**Comment by axmsoftware** [comment]
Hi John,

Could you share the calendar invite for the June 4th TAC meeting?

I want to make sure both Asimenia and Anto can attend as well for the joint
proposal.

Thank you,

Arila

**Comment by jmertic** [comment]
Hi @axmsoftware - you can goto the join link and request an invite to be sent to you...

https://zoom-lfx.platform.linuxfoundation.org/meeting/95214651568?password=eda16f17-bdd1-4a9f-a594-0947a1433153

Both of them should already be on the TAC invite.

**Comment by yarille** [comment]
Yarille to work with Arila on Hyphae transition.
