### ISSUE TITLE
TAC Evolution Plan

### ISSUE THREAD

**Issue by jmertic** [lf-energy/tac#116]
### Please share any additional details on this topic

Presentation of a plan to evolve the TAC

### Detail what actions or feedback you would like from the TAC

Feedback

### How much time do you need for this topic?

At least 30 minutes

**Comment by jmertic** [comment]
Latest plan version, which will be presented.

[TAC Evolution Plan - 2024-03-07.pdf](https://github.com/lf-energy/tac/files/14526943/TAC.Evolution.Plan.-.2024-03-07.pdf)

**Comment by yarille** [comment]
Approved by TAC vote 3/12
