### ISSUE TITLE
Transition to LFX Meeting Management for all projects

### ISSUE THREAD

**Issue by jmertic** [lf-energy/tac#39]
We are working to transition all hosted projects and working groups to using LFX Meeting Management for committee definition and meeting scheduling. The goal is to have all projects transitioned over by the end of the year.

Current Status:

Transitioned over (16):

- Archimate WG
- Arras
- CoMPAS
- Dynaωo
- EVerest
- FlexMeasures
- Hyphae
- OpenGEH 
- openLEADR
- OpenSTEF
- OperatorFabric
- Power Grid Model
- Real Time Data Ingestion Platform (RTDIP)
- SEAPATH
- Shapeshifter
- PowSyBl
- SOGNO

In Progress (0):

- _none_

TODO (4):

- FledgePOWER
- Grid Capacity Map
- Grid eXchange Fabric
- OpenEEmeter

**Comment by jmertic** [comment]
We now have a community calendar available through LFX Meetings...

https://zoom-lfx.platform.linuxfoundation.org/meetings/lf-energy

We will be replacing the existing community calendar at https://calendar.lfenergy.org with this ( same URL ), so project need to transition to this service to leverage it.

**Comment by krealyt** [comment]
Just a short question to this:
Looking at https://calendar.lfenergy.org/ currently, gives me "old" entries. I have moved my EVerest Framework Working Group to another days some weeks ago. But this seems not to have been updated there.

I guess, this will be updated when switching completely, right? Or are we able to edit the meeting dates somewhere?

**Comment by jmertic** [comment]
Hi - that calendar still points to the old calendar. I plan to transition
to the new one once the remaining projects are moved.
