### ISSUE TITLE
use Zulip instead of slack

### ISSUE THREAD

**Issue by caller** [lf-energy/tac#48]
### Please share any additional details on this topic

currently slack seems to be very little used by many LF(E) projects, and it is missing a history.
We got aware that for this and many other reasons the entire RUST community moved to the truely open source platform https://zulip.com and have been wondering if this might be something for LFE as well?

from EVerest perspecitve we have to choose something beyond mailinglist by probably early 2024, in order to cope with project growth.
thx
-Marco

### Detail what actions or feedback you would like from the TAC

decide to switch from slack to zulip and setup central infrastructure for all projects

### How much time do you need for this topic?

10 minutes or less

**Comment by Dominik-K** [comment]
They understood and fixed all the problems with Slack, Discord, Matrix/Element, etc. :

* asynchronous mode beside synchronous chats
* [searchable for search-engines](https://github.com/zulip/zulip-archive#why-archive)
* [no login needed to just read messages](https://blog.zulip.com/2022/05/05/public-access-option/)
* 100% open-source, not only open-core like e.g. Mattermost (open-source Slack replacement)

Some Rust teams migrated independently to Zulip, each at their own pace. They have been on Discord, Slack and perhaps others before. See https://zulip.com/case-studies/rust/

They offer [free hosting for open-source projects](https://zulip.com/for/open-source/). Exporting the whole organisation (from cloud hosting) to on-premise seems to be easy, AFAICS. See https://zulip.com/help/export-your-organization.


Good to read:

* https://blog.zulip.com/2022/05/05/public-access-option/
* https://zulip.com/why-zulip/
* HackerNews comments are also very positive. E.g. https://news.ycombinator.com/item?id=31572592 or https://news.ycombinator.com/item?id=27149123


What does the web-UI look like?:

* Rust development: https://rust-lang.zulipchat.com/   (and how do they introduce it: https://forge.rust-lang.org/platforms/zulip.html )
* Zulip development: https://chat.zulip.org/

**Comment by krealyt** [comment]
Handled in TAC meeting today.

**Discussion** around some potential improvements we could have with alternatives to Slack. E.g. history feature or better threading solution.

I described one **use case** for which history feature is required: Understand some tech architecture or technology decisions made in the past during discussions. Search for keywords in discussions for more that 90 days back.

I suggested that we as Pionix have a look into Zulip to see the features and eventually start evaluation. But we should only invest time if the meeting members do share those issues stated by us above.

Some feedback from the round:
"Personally I like slack a lot and would like to stay with Slack. What are other foundations doing regarding slack?"

"I wonder if message history is as much of a need as we are assuming. Open chat platforms are great for getting help quickly or pointed to some other resources like documentation. If there is important information shared in a chat platform that is needed long term, shouldn't it be put  into core documentation or another resource (GitHub issue for enhancement ideas or defects, etc.)"

"Maybe a tool like Confluence would be better for knowledgebase, ideas, meeting notes, How Tos, etc."


**General feedback summary**
No big need seen for moving away from Slack. Eventually, there are alternative approaches to meet requirements - see quotes above!


**ACTION**
Review the suggestions in the quotes above to see if we can implement alternative processes / tools to reach our goals. Do a first quick testing with Zulip inside of the EVerest project if still needed.

**Comment by jmertic** [comment]
Revisit with feedback from @caller at next TAC meeting

**Comment by jmertic** [comment]
Update - EVerest will trial this. Currently working through DP review internally.

**Comment by yarille** [comment]
Approved for use
