### ISSUE TITLE
CitrineOS EV Charging Management Software

### ISSUE THREAD

**Issue by OZHgood** [lf-energy/tac#59]
### Mission Statement

![231002_Citrine_OS_Logo_Citrine_Logo_positive-01](https://github.com/lf-energy/tac/assets/146758312/6ce0f1f2-c127-419b-90d4-0e0559621f57)

### Citrine OS: Empowering the Global EV Revolution with Open-Source Innovation 

At CitrineOS, our mission is to drive the transformation of the electric vehicle (EV) charging landscape, making it more attainable, equitable, and diverse than ever before. For over a decade, our parent company, S44, has been at the forefront of EV charging software, powering automotive OEMs and leading EV network operators. Now, through CitrineOS, we are taking a giant leap forward in advancing the adoption of electric vehicles and diversifying the EV charging infrastructure worldwide. 

### Who We Are  

CitrineOS, created by S44, is the brainchild of a dedicated team with deep expertise in EV charging technology. We understand the critical role that reliable back-end software plays in the world of EV charging. Our commitment to innovation and inclusivity drives us to make our solutions accessible to everyone.  

### What We Offer  

CitrineOS is more than just software; it's a catalyst for change. We are proud to offer our Open Charge Point Protocol (OCPP) 2.0.1 open source software on GitHub. This groundbreaking platform empowers a wide range of stakeholders, from passionate EV enthusiasts to the most prominent charge point operators, fleet managers, and automotive manufacturers.  

### With CitrineOS, you can:  

**1. Provision New Charging Equipment:** Seamlessly set up new charging stations, ensuring they're ready for action.  

**2. Complete Charging Transactions:** Enable secure and efficient EV charging experiences for users.  

**3. Remotely Control Charging Equipment:** Take charge of your charging infrastructure from anywhere, ensuring optimal performance.  

**4. Monitor Charger Equipment Uptime, Power Levels, and Degradation:** Keep a close eye on the health and efficiency of your charging stations.  

**5. Manage Energy Consumption and Throughput:** Optimize energy use and throughput, reducing environmental impact.  

### How We Do It  

Our modular software is meticulously designed based on real-world EV charging use cases. We understand the pressing need to enhance reliability and interoperability in EV charging ecosystems. CitrineOS is the ideal solution for achieving rapid compliance with National EV Infrastructure (NEVI) standards in both new and existing environments.  

  
### Why It Matters  

CitrineOS offers a multitude of benefits:  

**1. Rapid Deployment:** Set up a single charging point or an entire network 90% faster, ensuring that EV charging infrastructure keeps pace with the surging demand.  

**2. NEVI Compliance**: Meet aggressive federal NEVI timelines and standards for funding, securing essential resources to expand EV network.  

**3. Future-Proofing:** Avoid the pitfalls of vendor lock-in, ensuring that the charging network remains adaptable to evolving industry standards.  

**4. Cost Efficiency:**  Reduce runtime and operational costs by leveraging our cloud microservices architecture, streamlining management and maintenance.  

**5. Interoperability**: Embrace widespread interoperability, fostering seamless connections between various charging stations and CSMS. 

**6. Reliability:** Enhance reliability across the board with our common open source software backend.  

 
### Differentiator:  

In a world where proprietary solutions dominate the landscape, CitrineOS stands out as the first and only platform that offers a common, open source software foundation for all. Whether you're a passionate EV enthusiast or a major charge point operator, CitrineOS is your gateway to accelerate CPO deployments, future-proof your EV charging network, and ultimately contribute to a more sustainable and equitable future powered by electric vehicles.  

Join us in revolutionizing the EV charging ecosystem – together, we'll drive change for a cleaner, brighter tomorrow.  

### Is this a new project or an existing one?

CitrineOS is a new product.  

### Current lead(s)

N/A

### Sponsoring organization(s), along with any other key contributing individuals and/or organizations

S44

### Detail any existing community infrastructure, including:

- Connect with us on Discord: https://discord.gg/kkUxF7pRU7
- Visit our website: https://www.s44.team/citrineos
- Check out our Github account: https://github.com/citrineos

### Are there any specific infrastructure needs or requests outside of what is provided normally by LF Energy ? If so please detail them.

Outside of access to mailing lists, CitrineOS will not require additional support. 

### Why would this be a good candidate for inclusion in LF Energy?

CitrineOS is an ideal candidate for LF Energy because our mission of transforming EV charging aligns with LF Energy's goals of rapid decarbonization and sustainability. Leveraging a decade of EV charging software experience from our parent company, S44, we work towards equitable EV adoption, aligning with LF Energy's carbon reduction and clean energy objectives. Through innovation and open-source initiatives, we contribute to a cleaner and more prosperous energy ecosystem, reinforcing our commitment to sustainability and alignment with LF Energy's mission. 

### How would this benefit from inclusion in LF Energy?

CitrineOS will benefit from inclusion in LF Energy through: 

- Inclusion in LF Energy open source infrastructure 

- Reputation alignment  

- Partner identification (e.g. EVerest) 

- Community building for collaboration  

- Product lifecycle management 

### Provide a statement on alignment with the mission in the LF Energy charter.

At CitrineOS, we are committed to aligning with the mission outlined in the LF Energy charter. Our mission to drive the transformation of the electric vehicle (EV) charging landscape directly contributes to the goals of LF Energy. LF Energy is dedicated to creating a technology ecosystem that facilitates rapid decarbonization and promotes environmental sustainability, economic prosperity, and social well-being for future generations.  

By leveraging over a decade of experience in EV charging software through our parent company, S44, we are actively working towards making EV charging more attainable, equitable, and diverse. Our efforts to advance the adoption of electric vehicles and diversify the EV charging infrastructure worldwide directly align with LF Energy's objectives of reducing carbon emissions, promoting cleaner energy solutions, and fostering a more sustainable future. 

Through innovation, collaboration, and open-source initiatives, we are not only contributing to the transformation of the EV industry but also supporting the broader mission of LF Energy to create a cleaner, more prosperous, and socially responsible energy ecosystem for the benefit of all. Our commitment to aligning with LF Energy's mission underscores our dedication to a sustainable and equitable future for generations to come. 

### What specific need does this project address?

In our quest for a greener future, we face a pivotal challenge: by 2030, 50% of new U.S. cars will be EVs, but today 28% of chargers in leading cities don't work. Developers must build innovative software to improve and grow the charging network so EV owners can travel with confidence. CitrineOS provides the open source software to fuel this change. The project is NEVI compliant, globally available and open to all. 

CitrineOS offers a community-tested and reliable open source software for charger management which drives forward adoption of the OCPP 2.0.1 protocol resulting in more reliable charging networks worldwide. 

### Describe how this project impacts the energy industry.

When implemented it will broaden access to and utilization of EV charging networks while making it more secure, intelligent and manageable.  

### Describe how this project intersects with other LF Energy projects/working groups/special interest groups.

CitrineOS intersects with EVerest essentially by forming a holistic ecosystem for EV charging by covering both, the charger firmware and charger management software. 

Further, CitrineOS intersects with openLEADR to further integrate OpenADR into the charger management software to provide an intelligent and systematic approach for demand response. 

### Who are the potential benefactors of this project?

CitrineOS will benefit a number of groups: 

- Prospective Charge Point Operators (CPOs) seeking solutions to kick-start their EV charging projects.  

- Developers looking to work in electrification and EV charging. 

- The general public that is looking to leverage reliable and functioning charging stations.  

### What other organizations in the world should be interested in this project?

Additional organizations that would be interested in and benefit from CitrineOS include:

- Global energy companies 

- Local utility providers 

- Fleet operators 

### Plan for growing in maturity if accepted within LF Energy

- Engagement and code contribution by developer community 

- Market adoption 

- Expansion from OCPP central system to OCPI compliance, OpenADR, mobile app interfaces, and other 

- Hardware compatibility (e.g., various manufacturers) 

### Project license

Apache 2.0 

### Is the project's code available now? If so provide a link to the code location.

CitrineOS will be publicly available on October 18, 2023. 

### Does this project have ongoing public (or private) technical meetings?

N/A

### Does this project's community venues have a code of conduct? If so, please provide a link to it?

Community has not been opened yet and therefore the Code of Conduct has not been shared. However, once it is public, CitrineOS will provide a code of conduct to align all contributors. 

### Describe the project's leadership team and decision-making process.

CitrineOS strives to assemble an impactful leadership in addition to the designated Director of Open Source Project, Thana Paris. The decision-making process in the future will be determined by the community. 

### Does this project have public governance (more than just one organization)?

CitrineOS does not have public governance. 

### Does this project have a development schedule and/or release schedule?

As part of planned community launch of CitrineOS, a development schedule will assembled in collaboration with the developer community. 

### Does this project have dependencies on other open source projects? Which ones?

CitrineOS depends on various npm packages that are provided by other communities in order to facilitate data storage through ORM, message brokering amongst others. 

### Describe the project's documentation.

Upon community launch, CitrineOS will have the following: 

- ReadME describing project's intent and usage 

- Developer documentation with build and run instructions 

- API documentation for usage of system 

### Describe any trademarks associated with the project.

No trademarks associated with CitrineOS at present.  

### Do you have a project roadmap? If so please attach or provide a link.

Our immediate goal is to expand the project's OCPP 2.0.1 compliance. 

No project roadmap is available at present. It will be created with the community's input following the launch. 

### Are this project's roadmap and meeting minutes public posted?

No.

### Does this project have a legal entity and/or registered trademarks?

Not at present.

### Has this project been announced or promoted in any press?

Press promotion and outreach is embargoed, and will be published on October 18, 2023. 

### Does this project compete with other open source projects or commercial products?

To our knowledge, CitrineOS does not compete with any other open source projects.  The following commercial products would be considered a competitor: 

- Driivz 

- Ampeco 

- ChargeLab 

- Shell Recharge Solutions 

- EV Connect 

- ChargePoint 

Additionally, there are other open source projects related to OCPP (thank you to [@shankari](https://github.com/shankari) for pointing out that we should clarify this):

**EVerest**
EVerest is the charger-firmware side of OCPP instead of a CSMS like CitrineOS. We will be making sure CitrineOS is compatible with EVerest!

**MaEVe**
MaEVe was originally focused on ISO-15118-2 functionality only and has seen sporadic updates since pertaining to more general function as a CSMS using both OCPP 1.6 and 2.0.1. CitrineOS will distinguish itself with more active contributions and a clearer mission statement: CitrineOS aims to be a fully functional OCPP 2.0.1 CSMS.

**SteVe**
SteVe is a OCPP 1.6 CSMS. The difference between OCPP 1.6 and 2.0.1 is substantial, although they share things conceptually 2.0.1 is a full rewrite of 1.6 with many additional features. As such, we don't expect there to be much overlap between CitrineOS and SteVe for now. We encourage those looking for an OCPP 1.6 CSMS to use SteVe!

**Comment by jmertic** [comment]
Thank you! Scheduling for 10/28; will let you know if it can be moved to an earlier meeting

**Comment by shankari** [comment]
FYI to all, the GitHub is now public, so @OZHgood may want to update the links.

Also, it is not strictly true that there are no other open source projects in this space.
EVerest,an existing open-source project hosted by the LF tests itself against Steve (https://github.com/EVerest/EVerest/blob/d60bb2a274200f096d58948e5869c08e1a642891/docs/tutorials/how_to_ocpp/index.rst#run-everest-with-steve) and the mailing list has a discussion of integration with https://github.com/thoughtworks/maeve-csms

Steve in particular has ~ 600 stars and ~ 340 forks.

I can guess the differences between CitrineOS and these existing implementations, but it would be good to have them documented for the record.

**Comment by OZHgood** [comment]
Thank you for the feedback [@shankari](https://github.com/shankari)! We've updated the original post to reflect our now-released socials and added some clarification on the difference between CitrineOS and other OCPP open-source projects under our answer to **Does this project compete with other open source projects or commercial products?**

**Comment by yarille** [comment]
Project approved by TAC on 11/28 at Sandbox level.

**Comment by yarille** [comment]
Hi, @OZHgood  This issue was left open for your 2024 review date so we can keep track of it on the calendar.
