### ISSUE TITLE
Sylva project presentation

### ISSUE THREAD

**Issue by jmertic** [lf-energy/tac#61]
### Please share any additional details on this topic

Sylva is a project in LF Europe that is interested in collaboration with a number of our projects. It provides a layer for distributed cloud management.

https://sylvaproject.org/

### Detail what actions or feedback you would like from the TAC

Interest from hosted projects in collaboration with Sylva

### How much time do you need for this topic?

At least 30 minutes

**Comment by jmertic** [comment]
Working to reschedule

**Comment by GuillaumeNevic** [comment]
Sylva Objectives
High level architecture
Collaboration 
Achievements & Next Step
Any potential collaboration with LF Energy

**Comment by jmertic** [comment]
Awesome - thank you @GuillaumeNevic
