### ISSUE TITLE
OpenSCD

### ISSUE THREAD

**Issue by benvantende** [lf-energy/tac#86]
### Mission Statement

OpenSCD is a platform to enable fully digital substations - from design and commissioning through to maintenance and replacement

### Description

OpenSCD is an open-source, browser-based substation communication designer platform for editing IEC 61850 compatible Substation Configuration Language (SCL) files.

IEC 61850 is an international standard defining communication protocols, guidelines and datamodel for intelligent electronic devices (IED's) at electrical substations.

https://github.com/openscd/.github/blob/OpenSCDhistory/History.md

### Is this a new project or an existing one?

It is an existing project

### Current lead(s)

Maintainers: Pascal Wilbrink - Alliander https://github.com/pascalwilbrink and Tamás Rusz - SprintEins https://github.com/trusz

### Sponsoring organization(s), along with any other key contributing individuals and/or organizations

Alliander, Omicron, Transpower, TransnetBW, SprintEins

### Detail any existing community infrastructure, including:
  - Github/GitLab, or other location where the code is hosted
  - Website and/or docs
  - Communication channels ( such as Mailing lists, Slack, IRC )
  - Social Media Accounts

- https://github.com/openscd/
- https://openscd.org/
- LF Energy Slack #open-scd
- https://lists.lfenergy.org/g/CoMPAS/

### Are there any specific infrastructure needs or requests outside of what is provided normally by LF Energy ? If so please detail them.

Not for now; The current infrastructure/tooling options will fit for now.

### Why would this be a good candidate for inclusion in LF Energy?

OpenSCD is a good candidate because it fits perfectly together with the other projects classified as Digital Substation Automation Systems, like CoMPAS, SEAPATH and Fledge. OpenSCD joinin will increase the presence in this field.

### How would this benefit from inclusion in LF Energy?

It would make collaboration with other projects easier, it would be easier from a community perspective attracting developers to the project. The project would also benefit from a 'marketing' perspective, being able to use the LF Energy resources. Having a neutral collaboration organisation/infrastructure.

### Provide a statement on alignment with the mission in the LF Energy charter.

We would definitely like to remove barriers to adoption and for us that can be achieved by joining a larger foundation that trusted by many.

### What specific need does this project address?

The need to adhere to the IEC61850 System configuration language standard without the use of proprietary software and therefore reducing vendor-locking.

The plug-in architecture makes it easy for organisations to build their own plug-in and therefore tailor their engineering process to their needs. It allows vendor to add their vendor specific knowledge in a seperate plug-in.

Browser based: No need to install and manage seperate executables.

Enable/disable plug-ins: Ability to enable only the plug-in that are needed.

### Describe how this project impacts the energy industry.

The project aims to standardise the configuration of substations, reducing cost and speed of implementation. Many players in the field will be able to use this solution for free and having a large community to ask for feedback on specifc questions.

### Describe how this project intersects with other LF Energy projects/working groups/special interest groups.

Digital Substation Automation Systems, like CoMPAS, SEAPATH and FLedge

### Who are the potential benefactors of this project?

- DSO's - Distribution System Operators
- TSO's - Transmission System Operatos
- IED Vendors
- Engineering/integration companies e.g. building systems for DSO/TSO etc.
- Other IEC61850 SCL users (e.g. in the DER control domain)

### What other organizations in the world should be interested in this project?

See potential benefactors

### Plan for growing in maturity if accepted within LF Energy

If accepted and we can move ahead without having to care too much about administration and infrastructure we would love to focus on communicating the project and growing the community.

### Project license

Apache 2.0

### Is the project's code available now? If so provide a link to the code location.

https://github.com/openscd/

### Does this project have ongoing public (or private) technical meetings?

Yes, on a monthly basis

### Does this project's community venues have a code of conduct? If so, please provide a link to it?

https://github.com/openscd/.github/blob/main/profile/code_of_conduct.md

### Describe the project's leadership team and decision-making process.

The (Technical) Steering Committee consists of product owners of the companies that work on the project. The two previously mentioned maintainers have the power to push some decisions, but in general decisions are made in an agile manner

### Does this project have public governance (more than just one organization)?

Not current; We try to reach consensus, if this turns out to be hard, the maintainers will make a decision.

### Does this project have a development schedule and/or release schedule?

No; Release are currently made ad-hoc

### Does this project have dependencies on other open source projects? Which ones?

material, lit, ace-editor, panzoom, marked, open-wc standaard

### Describe the project's documentation.

https://github.com/openscd/open-scd/wiki Current

[Home · openscd/open-scd Wiki (github.com)](https://github.com/openscd/open-scd/wiki)

### Describe any trademarks associated with the project.

No trademarks

### Do you have a project roadmap? If so please attach or provide a link.

No; Just a bunch of idea's:

[Planned Features · Roadmap (github.com)](https://github.com/orgs/openscd/projects/10)

[open-scd/ROADMAP.md at main · openscd/open-scd (github.com)](https://github.com/openscd/open-scd/blob/main/ROADMAP.md)

### Are this project's roadmap and meeting minutes public posted?

Yes

### Does this project have a legal entity and/or registered trademarks?

No

### Has this project been announced or promoted in any press?

No; Search on Linkedin on OpenSCD for a white paper; The project is promoted by e.g. CoMPAS, Omicron and theirefore already known by a bunch of engineers.

### Does this project compete with other open source projects or commercial products?

Commercial partly competing: Siemens SITIPE, HELINKS, ASE Inc/Kalkitech, IED vendor tools

**Comment by jmertic** [comment]
Hi @benvantende - We've scheduled this for 30 Jan; let us know if this date works for you

**Comment by benvantende** [comment]
Hi @jmertic! Yes! Looking forward. Please, also invite @Sander3003. He is more from the tech details.

**Comment by jmertic** [comment]
Sounds good - @yarille will follow up on the slides and invites.

**Comment by yarille** [comment]
Presented to TAC- 12/19/2023. Project will be taken to the TAC for vote via email.

**Comment by Sander3003** [comment]
[231219 OpenSCD TAC proposal.pdf](https://github.com/lf-energy/tac/files/13726168/231219.OpenSCD.TAC.proposal.pdf)
Here are the slides

**Comment by Sander3003** [comment]
Where can I find a link to recording?

**Comment by yarille** [comment]
Vote to be postponed.

**Comment by Sander3003** [comment]
Is their an update on the vote?

**Comment by Sander3003** [comment]
How is the vote going? When can we expect a voting result?

**Comment by yarille** [comment]
@Sander3003 - approved by TAC email vote - 1/26/2024
