### ISSUE TITLE
OpenWallet / VC API presentation

### ISSUE THREAD

**Issue by jmertic** [lf-energy/tac#87]
More about the project at https://github.com/openwallet-foundation/project-proposals/blob/main/projects/vc-api-implementation.md

**Comment by jmertic** [comment]
Hi @jrhender - let me know if 20 February at 11:00 am US Eastern Time works for you to do this presentation

**Comment by jrhender** [comment]
Hi @jmertic apologies for the slow reply here. Yes, this time works for me, thank you.

**Comment by jmertic** [comment]
Excellent - thank you! @yarille please provide them the meeting details when you have a moment.

**Comment by jrhender** [comment]
Hi @jmertic and @yarille , is the presentation of OWF and VC API to the LF Energy TAC still planned for Feb 20th?

**Comment by jmertic** [comment]
Confirmed - let @yarille know if you need an invite for the call.

**Comment by jmertic** [comment]
Hi @jrhender - please share the slides and materials you plan to present in the meeting. Thanks!

**Comment by jrhender** [comment]
Hi @jmertic , here are the slides I plan on using:

1. https://openwallet.foundation/wp-content/uploads/sites/11/2024/01/2024-OpenWallet-Presentation.pdf
2. https://speakerdeck.com/jhenderson/owf-and-vc-api-at-linux-foundation-energy

I might tweak the second set of slides slightly before the presentation but that is mostly what I will use.

I plan to also to share a brief demo. I may try to do this live, or I may use a recording.

**Comment by jmertic** [comment]
Perfect - thank you! We will have you present from your screen if that's ok for you.

**Comment by jrhender** [comment]
@jmertic
> We will have you present from your screen if that's ok for you.

No problem 


Another request: Other folks from the OWF plan on joining to answer any questions that I don't know the answer to. However, they can only join 30 minutes into the meeting. Would it be possible cover the OWF/VC-API topic after other meeting topics to the OWF folks a better chance of joining for the OWF portion?

**Comment by jmertic** [comment]
Sure thing - I have you slated to go on at noon ET/6:00 pm CET if that is ok?

**Comment by jrhender** [comment]
Sounds great, thanks @jmertic
